/**
 * Sports fever
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Shankarmurthy.bhat@in.bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Question } from '../model/question';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class QuestionsService {

    protected basePath = 'http://bmh1054484.ban.apac.bosch.com:8000/spfever';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new question for a challenge
     * Create a new question for a challenge if it is a STAT_QUIZ
     * @param id Unique id for challenge
     * @param body the question to be created
     * @param authtoken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createNewQuestion(id: string, body: Question, authtoken?: string, observe?: 'body', reportProgress?: boolean): Observable<Question>;
    public createNewQuestion(id: string, body: Question, authtoken?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Question>>;
    public createNewQuestion(id: string, body: Question, authtoken?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Question>>;
    public createNewQuestion(id: string, body: Question, authtoken?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling createNewQuestion.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createNewQuestion.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (authtoken !== undefined) {
            queryParameters = queryParameters.set('authtoken', <any>authtoken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Question>(`${this.basePath}/challenges/${encodeURIComponent(String(id))}/questions`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes a question
     * Deletes a question
     * @param id Unique id for challenge
     * @param qId Unique id for question
     * @param authtoken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteQuestion(id: string, qId: string, authtoken?: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteQuestion(id: string, qId: string, authtoken?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteQuestion(id: string, qId: string, authtoken?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteQuestion(id: string, qId: string, authtoken?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteQuestion.');
        }
        if (qId === null || qId === undefined) {
            throw new Error('Required parameter qId was null or undefined when calling deleteQuestion.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (authtoken !== undefined) {
            queryParameters = queryParameters.set('authtoken', <any>authtoken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<boolean>(`${this.basePath}/challenges/${encodeURIComponent(String(id))}/questions/${encodeURIComponent(String(qId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a question
     * Get a question a challenge if it is a STAT_QUIZ
     * @param id Unique id for challenge
     * @param qId Unique id for question
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getQuestion(id: string, qId: string, observe?: 'body', reportProgress?: boolean): Observable<Question>;
    public getQuestion(id: string, qId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Question>>;
    public getQuestion(id: string, qId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Question>>;
    public getQuestion(id: string, qId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getQuestion.');
        }
        if (qId === null || qId === undefined) {
            throw new Error('Required parameter qId was null or undefined when calling getQuestion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Question>(`${this.basePath}/challenges/${encodeURIComponent(String(id))}/questions/${encodeURIComponent(String(qId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all the questions for a challenge
     * Gets all the questions for a challenge if it is a STAT_QUIZ
     * @param id Unique id for challenge
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getQuestions(id: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Question>>;
    public getQuestions(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Question>>>;
    public getQuestions(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Question>>>;
    public getQuestions(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getQuestions.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Question>>(`${this.basePath}/challenges/${encodeURIComponent(String(id))}/questions`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates a qustion
     * Updates a qustion of a challenge if it is a STAT_QUIZ
     * @param id Unique id for challenge
     * @param qId Unique id for question
     * @param body the question to be created
     * @param authtoken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateQuestion(id: string, qId: string, body: Question, authtoken?: string, observe?: 'body', reportProgress?: boolean): Observable<Question>;
    public updateQuestion(id: string, qId: string, body: Question, authtoken?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Question>>;
    public updateQuestion(id: string, qId: string, body: Question, authtoken?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Question>>;
    public updateQuestion(id: string, qId: string, body: Question, authtoken?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateQuestion.');
        }
        if (qId === null || qId === undefined) {
            throw new Error('Required parameter qId was null or undefined when calling updateQuestion.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateQuestion.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (authtoken !== undefined) {
            queryParameters = queryParameters.set('authtoken', <any>authtoken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<Question>(`${this.basePath}/challenges/${encodeURIComponent(String(id))}/questions/${encodeURIComponent(String(qId))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
