/**
 * Sports fever
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Shankarmurthy.bhat@in.bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { UserChallengeAnswer } from '../model/userChallengeAnswer';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserChallengeAnswerService {

    protected basePath = 'http://10.165.3.147:8000/spfever';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Creates a new userChallengeAnswer.
     * 
     * @param body 
     * @param authtoken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUserChallengeAnswer(body?: UserChallengeAnswer, authtoken?: string, observe?: 'body', reportProgress?: boolean): Observable<UserChallengeAnswer>;
    public createUserChallengeAnswer(body?: UserChallengeAnswer, authtoken?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserChallengeAnswer>>;
    public createUserChallengeAnswer(body?: UserChallengeAnswer, authtoken?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserChallengeAnswer>>;
    public createUserChallengeAnswer(body?: UserChallengeAnswer, authtoken?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (authtoken !== undefined) {
            queryParameters = queryParameters.set('authtoken', <any>authtoken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UserChallengeAnswer>(`${this.basePath}/userChallengeAnswers`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes a userChallengeAnswer based on the project id.
     * Deletes a userChallengeAnswer based on the userChallengeAnswer id from file system.
     * @param id A userChallengeAnswer’s unique id to delete a userChallengeAnswer
     * @param authtoken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUserChallengeAnswer(id: string, authtoken?: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteUserChallengeAnswer(id: string, authtoken?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteUserChallengeAnswer(id: string, authtoken?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteUserChallengeAnswer(id: string, authtoken?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteUserChallengeAnswer.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (authtoken !== undefined) {
            queryParameters = queryParameters.set('authtoken', <any>authtoken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<boolean>(`${this.basePath}/userChallengeAnswers/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves a userChallengeAnswer on ID.
     * 
     * @param id A userChallengeAnswer’s unique id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserChallengeAnswer(id: string, observe?: 'body', reportProgress?: boolean): Observable<UserChallengeAnswer>;
    public getUserChallengeAnswer(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserChallengeAnswer>>;
    public getUserChallengeAnswer(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserChallengeAnswer>>;
    public getUserChallengeAnswer(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getUserChallengeAnswer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<UserChallengeAnswer>(`${this.basePath}/userChallengeAnswers/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves all UserChallengeAnswers
     * Retrieves all UserChallengeAnswers
     * @param filterByUser provide data to filter result
     * @param filterByChallenge provide data to filter result
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserChallengeAnswers(filterByUser?: string, filterByChallenge?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<UserChallengeAnswer>>;
    public getUserChallengeAnswers(filterByUser?: string, filterByChallenge?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserChallengeAnswer>>>;
    public getUserChallengeAnswers(filterByUser?: string, filterByChallenge?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserChallengeAnswer>>>;
    public getUserChallengeAnswers(filterByUser?: string, filterByChallenge?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (filterByUser !== undefined) {
            queryParameters = queryParameters.set('filterByUser', <any>filterByUser);
        }
        if (filterByChallenge !== undefined) {
            queryParameters = queryParameters.set('filterByChallenge', <any>filterByChallenge);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<UserChallengeAnswer>>(`${this.basePath}/userChallengeAnswers`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates the details of a userChallengeAnswer.
     * Updates the details of a userChallengeAnswer. 
     * @param id A userChallengeAnswer’s unique id to update a userChallengeAnswer
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUserChallengeAnswer(id: string, body?: UserChallengeAnswer, observe?: 'body', reportProgress?: boolean): Observable<UserChallengeAnswer>;
    public updateUserChallengeAnswer(id: string, body?: UserChallengeAnswer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserChallengeAnswer>>;
    public updateUserChallengeAnswer(id: string, body?: UserChallengeAnswer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserChallengeAnswer>>;
    public updateUserChallengeAnswer(id: string, body?: UserChallengeAnswer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateUserChallengeAnswer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<UserChallengeAnswer>(`${this.basePath}/userChallengeAnswers/${encodeURIComponent(String(id))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
