/**
 * Sports fever
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Shankarmurthy.bhat@in.bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Image {
    id?: string;
    type?: Image.TypeEnum;
    name?: string;
    url?: string;
}
export namespace Image {
    export type TypeEnum = 'JPEG' | 'PNG' | 'BMP' | 'GIF';
    export const TypeEnum = {
        JPEG: 'JPEG' as TypeEnum,
        PNG: 'PNG' as TypeEnum,
        BMP: 'BMP' as TypeEnum,
        GIF: 'GIF' as TypeEnum
    }
}
