/**
 * Sports fever
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Shankarmurthy.bhat@in.bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Stadium } from './stadium';


export interface Match {
    id?: string;
    name?: string;
    type?: Match.TypeEnum;
    date?: string;
    team1?: string;
    team2?: string;
    stadium?: Stadium;
    team1Result?: number;
    team2Result?: number;
}
export namespace Match {
    export type TypeEnum = 'GROUP' | 'KNOCKOUT';
    export const TypeEnum = {
        GROUP: 'GROUP' as TypeEnum,
        KNOCKOUT: 'KNOCKOUT' as TypeEnum
    }
}
