/**
 * Sports fever
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Shankarmurthy.bhat@in.bosch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserAnswer } from './userAnswer';


export interface UserChallengeAnswer {
    id?: string;
    userid?: string;
    matchId?: string;
    challengeId?: string;
    answerS?: string;
    coinsBet?: string;
    coinsWon?: string;
    answerType?: UserChallengeAnswer.AnswerTypeEnum;
    answers?: Array<UserAnswer>;
}
export namespace UserChallengeAnswer {
    export type AnswerTypeEnum = 'SINGLE' | 'MULTIPLE';
    export const AnswerTypeEnum = {
        SINGLE: 'SINGLE' as AnswerTypeEnum,
        MULTIPLE: 'MULTIPLE' as AnswerTypeEnum
    }
}
